FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY bot.py bot.py
COPY parser.py parser.py

CMD ["python", "bot.py"]